### ISSUE TITLE
A lot of dup functionality with EDColor

### ISSUE THREAD

**Issue by dblock** [pixelslip/Colorkit#1]
There's quite a bit of dup functionality with https://github.com/thisandagain/color. We've been trying to assemble a good color utility library for quite a bit with tests & al. Might want to consider merging a few things in.

**Comment by pixelslip** [comment]
Nice lib indeed, I will pull request with my code. Thanks for the link.

**Comment by pixelslip** [comment]
There is a lot of duplicate functions I admit (quite normal because it's a manipulation colors library), but i don't understand why you want to add darken, lighten, saturate and spin. 
These are already in **UIColor+HSL.h**:  _offsetWithHue:saturation:lightness:alpha_

The only thing I can add, it's a sort of rewrite methods like so:

<pre><code>- (UIColor *)saturate:(CGFloat)amount
{
    return [self offsetWithHue:0.0f saturation:[self clamp:amount] lightness:0.0f alpha:0.0f];
}</code></pre>

**Comment by dblock** [comment]
@pixelslip I didn't dig deep into this, you should add the functions that make sense. From the API POV I wouldn't hesitate to add methods that are easier to understand, eg. `saturate` or `darken`, cause `offsetWithHue` is rather thick :)
